name: Deploy via SSH to Cloudways

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Deploy to Cloudways
      run: |
        ssh -o StrictHostKeyChecking=yes ${{ secrets.SFTP_USERNAME }}@${{ secrets.SSH_HOST }} \
        "cd /home/${{ secrets.SFTP_USERNAME }}/applications/bnrzkepymx/public_html && git pull origin main"
